# created by shubham_malik_123456
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: step-security/harden-runner@v1
        with:
          egress-policy: audit
      - name: Buildah action
        uses: redhat-actions/buildah-build@v2
        with:
          base-image: docker.io/fabric8/java-alpine-openjdk11-jre
          image: my-new-image
          tags: v1
          content: |
            target/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar
          entrypoint: java -jar spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar
          port: 8080
